<?php
/* Copyright (C) 2007-2017 Laurent Destailleur  <eldy@users.sourceforge.net>
 * Copyright (C) 2019      Gabriel Carpio		<gabriel@quantumbit.mx>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *   	\file       htdocs/autotran/index.php
 *		\ingroup    autotran
 *		\brief      Lista para facturas de pago
 */


// Load Dolibarr environment
include('../main.inc.php');

require_once(DOL_DOCUMENT_ROOT.'/core/class/html.formcompany.class.php');
require_once DOL_DOCUMENT_ROOT.'/core/lib/date.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/company.lib.php';
include_once "class/facturas.class.php";
include_once "admin/helper/conexionex.php";

$action     = GETPOST('action','aZ09')?GETPOST('action','aZ09'):'view';				// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = GETPOST('massaction','alpha');											// The bulk action (combo box choice into lists)
$show_files = GETPOST('show_files','int');												// Show files area generated by bulk actions ?
$confirm    = GETPOST('confirm','alpha');												// Result of a confirmation
$cancel     = GETPOST('cancel', 'alpha');												// We click on a Cancel button
$toselect   = GETPOST('toselect', 'array');												// Array of ids of elements selected into a list
if (! empty($contextpage) && $contextpage != $_SERVER["PHP_SELF"]) $param.='&contextpage='.urlencode($contextpage);   // To manage different context of search
$backtopage = GETPOST('backtopage','alpha');											// Go back to a dedicated page
$optioncss  = GETPOST('optioncss','aZ');												// Option for the css output (always '' except when 'print')

$id			= GETPOST('id','int');

// Load variable for pagination
$limit = GETPOST('limit','int')?GETPOST('limit','int'):$conf->liste_limit;
$sortfield = GETPOST('sortfield','alpha');
$sortorder = GETPOST('sortorder','alpha');
$page = GETPOST('page','int');
if (empty($page) || $page == -1 || GETPOST('button_search','alpha') || GETPOST('button_removefilter','alpha') || (empty($toselect) && $massaction === '0')) { $page = 0; }     // If $page is not defined, or '' or -1 or if we click on clear filters or if we select empty mass action
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;

//// Initialize technical objects
$now=dol_now();

$query3 = "UPDATE ".MAIN_DB_PREFIX ."autotran_parametros SET FechaUltimaActualizacion = '".$fechaformato."' WHERE organizacionRFC = '".$conf->global->MAIN_INFO_SIREN."'";
$query2 = "SELECT MsgError FROM sys_autotran_parametros WHERE organizacionRFC = '".$conf->global->MAIN_INFO_SIREN."'";
$link = new conexionex();
	$res = $link ->consultarTabla($query2);
	$consultaParams['MsgError'][0] = $res['MsgError'];
	$consultaParams['UltimaVerificacion'][0] = $hoy;
	if($res['MsgError'] == ''||$res['MsgError'] == null||$res['MsgError'] == ' ')
	{
		$query2 = "SELECT FolioFiscal,Concepto,RFCemisor, NombreEmisor,RFCreceptor,NombreReceptor,fechaemision,fechaCertificacion,PAC,Total,Efecto,Estado FROM sys_autotran_facturas WHERE organizacionRFC = '".$conf->global->MAIN_INFO_SIREN."'";
		$tab = $link -> escribirTabla($query2);
		//print_r($tab);
		$i = 0;
		$query1 = "";
		while($i < count($tab))
		{
		//print_r($tab[$i]['fechaemision']);
		$query1 = "";
		$query1.= "INSERT INTO ". MAIN_DB_PREFIX ."autotran_facturas";
		$query1.= "(organizacionId, Concepto, FolioFiscal , RFCemisor, NombreEmisor, RFCreceptor ,NombreReceptor , FechaEmision ,FechaCertificacion , PAC ,Total, Efecto,Estado,RFCorganizacion,rowId)";
		$query1.="VALUES(1,".$tab[$i]['Concepto'].",'".$tab[$i]['FolioFiscal']."','".$tab[$i]['RFCemisor']."','".$tab[$i]['NombreEmisor']."','".$tab[$i]['RFCreceptor']."','".$tab[$i]['NombreReceptor']."','";
		$query1.=$tab[$i]['fechaemision']."','".$tab[$i]['fechaCertificacion']."','".$tab[$i]['PAC']."','".$tab[$i]['Total']."','".$tab[$i]['Efecto']."','".$tab[$i]['Estado']."',";
		$query1.="'".$conf->global->MAIN_INFO_SIREN."', 0);";
		//print_r($query1);
		$db->query($query1);
		$i++;
		}
		$db->query($query3);		
	}
$object = new facturas($db);

// Default sort order (if not yet defined by previous GETPOST)
if (! $sortfield) $sortfield="t.".key($object->fields);   // Set here default search field. By default 1st field in definition.
if (! $sortorder) $sortorder="ASC";

// Security check
$socid=0;
if ($user->societe_id > 0)	// Protection if external user
{
	//$socid = $user->societe_id;
	accessforbidden();
}

// Initialize array of search criterias
$search_all=trim(GETPOST("search_all",'alpha'));
$search=array();
foreach($object->fields as $key => $val)
{
	if (GETPOST('search_'.$key,'alpha')) $search[$key]=GETPOST('search_'.$key,'alpha');
}

// List of fields to search into when doing a "search in all"
$fieldstosearchall = array();
foreach($object->fields as $key => $val)
{
	if ($val['searchall']) $fieldstosearchall['t.'.$key]=$val['label'];
}

// Definition of fields for list
$arrayfields=array();
foreach($object->fields as $key => $val)
{
	if (! empty($val['visible'])) $arrayfields['t.'.$key]=array('label'=>$val['label'], 'checked'=>(($val['visible']<0)?0:1), 'enabled'=>$val['enabled'], 'position'=>$val['position']);
}
// Extra fields
if (is_array($extrafields->attributes[$object->table_element]['label']) && count($extrafields->attributes[$object->table_element]['label']) > 0)
{
	foreach($extrafields->attributes[$object->table_element]['label'] as $key => $val)
	{
		if (! empty($extrafields->attributes[$object->table_element]['list'][$key]))
			$arrayfields["ef.".$key]=array('label'=>$extrafields->attributes[$object->table_element]['label'][$key], 'checked'=>(($extrafields->attributes[$object->table_element]['list'][$key]<0)?0:1), 'position'=>$extrafields->attributes[$object->table_element]['pos'][$key], 'enabled'=>(abs($extrafields->attributes[$object->table_element]['list'][$key])!=3 && $extrafields->attributes[$object->table_element]['perms'][$key]));
	}
}
$object->fields = dol_sort_array($object->fields, 'position');
$arrayfields = dol_sort_array($arrayfields, 'position');



/*
 * Actions
 */

if (GETPOST('cancel','alpha')) { $action='list'; $massaction=''; }
if (! GETPOST('confirmmassaction','alpha') && $massaction != 'presend' && $massaction != 'confirm_presend') { $massaction=''; }

$parameters=array();
$reshook=$hookmanager->executeHooks('doActions', $parameters, $object, $action);    // Note that $action and $object may have been modified by some hooks
if ($reshook < 0) setEventMessages($hookmanager->error, $hookmanager->errors, 'errors');

if (empty($reshook))
{
	// Selection of new fields
	include DOL_DOCUMENT_ROOT.'/core/actions_changeselectedfields.inc.php';

	// Purge search criteria
	if (GETPOST('button_removefilter_x','alpha') || GETPOST('button_removefilter.x','alpha') ||GETPOST('button_removefilter','alpha')) // All tests are required to be compatible with all browsers
	{
		foreach($object->fields as $key => $val)
		{
			$search[$key]='';
		}
		$toselect='';
		$search_array_options=array();
	}
	if (GETPOST('button_removefilter_x','alpha') || GETPOST('button_removefilter.x','alpha') || GETPOST('button_removefilter','alpha')
		|| GETPOST('button_search_x','alpha') || GETPOST('button_search.x','alpha') || GETPOST('button_search','alpha'))
	{
		$massaction='';     // Protection to avoid mass action if we force a new search during a mass action confirmation
	}

	// Mass actions
	$objectclass='XML';
	$objectlabel='XML';
	$permtoread = $user->rights->autotran->read;
	$permtodelete = $user->rights->autotran->delete;
	$uploaddir = $conf->autotran->dir_output;
	include DOL_DOCUMENT_ROOT.'/core/actions_massactions.inc.php';
}



/*
 * View
 */

$form=new Form($db);

$now=dol_now();

$title = $langs->trans('ListOf', $langs->transnoentitiesnoconv("Facturas SAT"));


// Build and execute select
// --------------------------------------------------------------------
$sql = 'SELECT ';
foreach($object->fields as $key => $val)
{
	$sql.='t.'.$key.', ';
}
// Add fields from extrafields
if (! empty($extrafields->attributes[$object->table_element]['label']))
	foreach ($extrafields->attributes[$object->table_element]['label'] as $key => $val) $sql.=($extrafields->attributes[$object->table_element]['type'][$key] != 'separate' ? "ef.".$key.' as options_'.$key.', ' : '');
// Add fields from hooks
$parameters=array();
$reshook=$hookmanager->executeHooks('printFieldListSelect', $parameters, $object);    // Note that $action and $object may have been modified by hook
$sql.=$hookmanager->resPrint;
$sql=preg_replace('/, $/','', $sql);
$sql.= " FROM ".MAIN_DB_PREFIX.$object->table_element." as t";
if (is_array($extrafields->attributes[$object->table_element]['label']) && count($extrafields->attributes[$object->table_element]['label'])) $sql.= " LEFT JOIN ".MAIN_DB_PREFIX.$object->table_element."_extrafields as ef on (t.rowid = ef.fk_object)";
if ($object->ismultientitymanaged == 1) $sql.= " WHERE t.entity IN (".getEntity($object->element).")";
else $sql.=" WHERE 1";
foreach($search as $key => $val)
{
	if ($key == 'status' && $search[$key] == -1) continue;
	$mode_search=(($object->isInt($object->fields[$key]) || $object->isFloat($object->fields[$key]))?1:0);
	if ($search[$key] != '') $sql.=natural_search($key, $search[$key], (($key == 'status')?2:$mode_search));
}
if ($search_all) $sql.= natural_search(array_keys($fieldstosearchall), $search_all);
// Add where from extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_sql.tpl.php';
// Add where from hooks
$parameters=array();
$reshook=$hookmanager->executeHooks('printFieldListWhere', $parameters, $object);    // Note that $action and $object may have been modified by hook
$sql.=$hookmanager->resPrint;
if(! empty($sortfield) && $sortfield != 't.')
{
	$sql.=$db->order($sortfield,$sortorder);
}


// Count total nb of records
$nbtotalofrecords = '';
//print_r($sql);
if (empty($conf->global->MAIN_DISABLE_FULL_SCANLIST))
{
	$resql = $db->query($sql);
	$nbtotalofrecords = $db->num_rows($resql);
	if (($page * $limit) > $nbtotalofrecords)	// if total of record found is smaller than page * limit, goto and load page 0
	{
		$page = 0;
		$offset = 0;
	}
}
// if total of record found is smaller than limit, no need to do paging and to restart another select with limits set.
if (is_numeric($nbtotalofrecords) && $limit > $nbtotalofrecords)
{
	$num = $nbtotalofrecords;
}
else
{
	$sql.= $db->plimit($limit+1, $offset);

	$resql=$db->query($sql);
	if (! $resql)
	{
		dol_print_error($db);
		exit;
	}

	$num = $db->num_rows($resql);
}

// Direct jump if only one record found
if ($num == 1 && ! empty($conf->global->MAIN_SEARCH_DIRECT_OPEN_IF_ONLY_ONE) && $search_all)
{
	$obj = $db->fetch_object($resql);
	$id = $obj->rowId;
	header("Location: ".dol_buildpath('/fourn/facture/card.php', 1).'?id='.$id);
	exit;
}


// Output page
// --------------------------------------------------------------------

llxHeader("",$langs->trans("AutoTran"));

// Example : Adding jquery code
print '<script type="text/javascript" language="javascript">
jQuery(document).ready(function() {
	function init_myfunc()
	{
		jQuery("#myid").removeAttr(\'disabled\');
		jQuery("#myid").attr(\'disabled\',\'disabled\');
	}
	init_myfunc();
	jQuery("#mybutton").click(function() {
		init_myfunc();
	});
});
</script>';

$arrayofselected=is_array($toselect)?$toselect:array();

$param='';
if (! empty($contextpage) && $contextpage != $_SERVER["PHP_SELF"]) $param.='&contextpage='.urlencode($contextpage);
if ($limit > 0 && $limit != $conf->liste_limit) $param.='&limit='.urlencode($limit);
foreach($search as $key => $val)
{
	$param.= '&search_'.$key.'='.urlencode($search[$key]);
}
if ($optioncss != '')     $param.='&optioncss='.urlencode($optioncss);
// Add $param from extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_param.tpl.php';
// List of mass actions available
$arrayofmassactions =  array(
	//'presend'=>$langs->trans("SendByMail"),
	//'builddoc'=>$langs->trans("PDFMerge"),
);
if ($user->rights->mymodule->delete) $arrayofmassactions['predelete']=$langs->trans("Delete");
if (GETPOST('nomassaction','int') || in_array($massaction, array('presend','predelete'))) $arrayofmassactions=array();
$massactionbutton=$form->selectMassAction('', $arrayofmassactions);

print '<form method="POST" id="searchFormList" action="'.$_SERVER["PHP_SELF"].'">';
if ($optioncss != '') print '<input type="hidden" name="optioncss" value="'.$optioncss.'">';
print '<input type="hidden" name="token" value="'.$_SESSION['newtoken'].'"><script src="js/ajax.js"></script>';
print '<input type="hidden" name="formfilteraction" id="formfilteraction" value="list">';
print '<input type="hidden" name="action" value="list">';
print '<input type="hidden" name="sortfield" value="'.$sortfield.'">';
print '<input type="hidden" name="sortorder" value="'.$sortorder.'">';
print '<input type="hidden" name="page" value="'.$page.'">';
print '<input type="hidden" name="contextpage" value="'.$contextpage.'">';

print_barre_liste($title, $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, 'title_companies', 0, $newcardbutton, '', $limit);

if ($sall)
{
	foreach($fieldstosearchall as $key => $val) $fieldstosearchall[$key]=$langs->trans($val);
	print '<div class="divsearchfieldfilter">'.$langs->trans("FilterOnInto", $sall) . join(', ',$fieldstosearchall).'</div>';
}

$moreforfilter = '';

$parameters=array();
$reshook=$hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object);    // Note that $action and $object may have been modified by hook
if (empty($reshook)) $moreforfilter .= $hookmanager->resPrint;
else $moreforfilter = $hookmanager->resPrint;

if (! empty($moreforfilter))
{
	print '<div class="liste_titre liste_titre_bydiv centpercent">';
	print $moreforfilter;
	print '</div>';
}

$varpage=empty($contextpage)?$_SERVER["PHP_SELF"]:$contextpage;
$selectedfields=$form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage);	// This also change content of $arrayfields
$selectedfields.=(count($arrayofmassactions) ? $form->showCheckAddButtons('checkforselect', 1) : '');

print '<div class="div-table-responsive">';		// You can use div-table-responsive-no-min if you dont need reserved height for your table
print '<table class="tagtable liste'.($moreforfilter?" listwithfilterbefore":"").'">'."\n";


// Fields title search
// --------------------------------------------------------------------
print '<tr class="liste_titre">';
foreach($object->fields as $key => $val)
{
	$cssforfield='';
	if (in_array($val['type'], array('date','datetime','timestamp'))) $cssforfield.=($cssforfield?' ':'').'center';
	if (in_array($val['type'], array('timestamp'))) $cssforfield.=($cssforfield?' ':'').'nowrap';
	if ($key == 'status') $cssforfield.=($cssforfield?' ':'').'center';
	if (! empty($arrayfields['t.'.$key]['checked'])) print '<td class="liste_titre'.($cssforfield?' '.$cssforfield:'').'"><input type="text" class="flat maxwidth75" name="search_'.$key.'" value="'.dol_escape_htmltag($search[$key]).'"></td>';
}
// Extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_input.tpl.php';

// Fields from hook
$parameters=array('arrayfields'=>$arrayfields);
$reshook=$hookmanager->executeHooks('printFieldListOption', $parameters, $object);    // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;
// Action column
print '<td class="liste_titre" align="right">';
$searchpicto=$form->showFilterButtons();
print $searchpicto;
print '</td>';
print '</tr>'."\n";


// Fields title label
// --------------------------------------------------------------------
print '<tr class="liste_titre">';
foreach($object->fields as $key => $val)
{
	$cssforfield='';
	if (in_array($val['type'], array('date','datetime','timestamp'))) $cssforfield.=($cssforfield?' ':'').'center';
	if (in_array($val['type'], array('timestamp'))) $cssforfield.=($cssforfield?' ':'').'nowrap';
	if ($key == 'status') $cssforfield.=($cssforfield?' ':'').'center';
	if (! empty($arrayfields['t.'.$key]['checked']))
	{
		print getTitleFieldOfList($arrayfields['t.'.$key]['label'], 0, $_SERVER['PHP_SELF'], 't.'.$key, '', $param, ($cssforfield?'class="'.$cssforfield.'"':''), $sortfield, $sortorder, ($cssforfield?$cssforfield.' ':''))."\n";
	}
}
// Extra fields
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_search_title.tpl.php';
// Hook fields
$parameters=array('arrayfields'=>$arrayfields,'param'=>$param,'sortfield'=>$sortfield,'sortorder'=>$sortorder);
$reshook=$hookmanager->executeHooks('printFieldListTitle', $parameters, $object);    // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;
print getTitleFieldOfList($selectedfields, 0, $_SERVER["PHP_SELF"],'','','','align="center"',$sortfield,$sortorder,'maxwidthsearch ')."\n";
print '</tr>'."\n";


// Detect if we need a fetch on each output line
$needToFetchEachLine=0;
if (is_array($extrafields->attributes[$object->table_element]['computed']) && count($extrafields->attributes[$object->table_element]['computed']) > 0)
{
	foreach ($extrafields->attributes[$object->table_element]['computed'] as $key => $val)
	{
		if (preg_match('/\$object/',$val)) $needToFetchEachLine++;  // There is at least one compute field that use $object
	}
}


// Loop on record
// --------------------------------------------------------------------
$i=0;
$totalarray=array();
$terceroscreados = false;
while ($i < min($num, $limit))
{
	$obj = $db->fetch_object($resql);
	if (empty($obj)) break;	
		// Should not happen
	//print_r($obj);
	//print_r($obj->rowId);
	// Store properties in $object
	$object->id = $obj->rowId;
	foreach($object->fields as $key => $val)
	{
		if (isset($obj->$key)) $object->$key = $obj->$key;
	}

	// Show here line of result
	print '<tr class="oddeven">';
	$numFact = 0;
	foreach($object->fields as $key => $val)
	{
		$cssforfield='';
	    if (in_array($val['type'], array('date','datetime','timestamp'))) $cssforfield.=($cssforfield?' ':'').'center';
	    elseif ($key == 'status') $cssforfield.=($cssforfield?' ':'').'center';
	    
	    if (in_array($val['type'], array('timestamp'))) $cssforfield.=($cssforfield?' ':'').'nowrap';
	    elseif ($key == 'ref') $cssforfield.=($cssforfield?' ':'').'nowrap';
	    
	    if (! empty($arrayfields['t.'.$key]['checked']))
		{
			print '<td';
			if ($cssforfield || $val['css']) print ' class="';
			print $cssforfield;
			if ($cssforfield && $val['css']) print ' ';
			print $val['css'];
			if ($cssforfield || $val['css']) print '"';
			print '>';
			
			if($arrayfields['t.'.$key]['label'] == 'Factura')
			{
				if($obj->Factura == "")
				{
					if($obj->Estado != "Cancelado")
					{
						$tsql="SELECT f.rowid as row,f.ref as ref,f.total_ttc as total FROM ".MAIN_DB_PREFIX."facture_fourn AS f ";
						$tsql.="INNER JOIN ".MAIN_DB_PREFIX."societe AS s ";
						$tsql.="ON f.fk_soc = s.rowid ";
						$tsql.="AND s.siren = '".$obj->RFCemisor."' ";
						$tsql.="WHERE ref NOT IN (SELECT Factura FROM ";
						$tsql.="llx_autotran_facturas WHERE Factura is NOT null) AND ref NOT LIKE '%PROV%'";
						$fact = array();
						$tc1= $db->query($tsql);
						if($tc1)
						{
							$nm1 = $db->num_rows($tc1);
							$i1 = 0;
							if($nm1)
							{
									while($i1 < $nm1)
									{
										$ojt = $db->fetch_object($tc1);
										if($ojt)
										{
											$fact[$i1] = array($ojt->row,$ojt->ref,$ojt->total);
											
										}
										$i1++;
									}
							}
					print '<div id="actualizar'.$obj->rowId.'"><select id="factura'.$obj->rowId.'" action = "autotranindex.php?action=nuevo" onchange="Registrar(\''.$obj->FolioFiscal.'\' , $(\'#factura'.$obj->rowId.'\').val(),\''.$obj->rowId.'\',\''.$obj->Total.'\',\''.$conf->global->MAIN_INFO_SIREN.'\')">
                    <option value="" disabled selected>--Seleccione--</option>
                    <option value="n" >--Crear Nueva--</option>';
                    for($i2 = 0 ;$i2< count($fact); $i2++)
                    {
                        print '<option value="'.$fact[$i2][1].' '.$fact[$i2][2].'" >'.$fact[$i2][1]. ' Total: $'.substr($fact[$i2][2],0,-6).'</option>';
                    }
						}
					}
				}
				else
				{
					$tsql0="SELECT rowid FROM ".MAIN_DB_PREFIX."facture_fourn WHERE ref='".$obj->Factura."'";
					$tc0= $db->query($tsql0);
					if($tc0)
							{
								$nm0 = $db->num_rows($tc0);
								if($nm0)
								{
									$objt0 = $db->fetch_object($tc0);
									if($objt0)
									{
										print "<a href='../fourn/facture/card.php?id=".$objt0->rowid."'>".$object->showOutputField($val, $key, $obj->$key, '')."</a>";
										print '<input type ="image" id="quitar'.$objt0->rowid.'" src="../theme/md/img/delete.png" onclick = "QuitarFactura(\''.$obj0->rowid.'\')"/>';
										$numFact = $objt0->rowid;
										
									}
								}				
							}
				}
				
				
			}
			else if($arrayfields['t.'.$key]['label'] == 'Poliza')
			{
				if($obj->Poliza != "")
				{
					$numpol = 0;
					$anioPol = 0;
					$mesPol = "0";
					$tipoP = "N";
					$qry = "SELECT anio,mes,tipo_pol,cons FROM llx_contab_polizas WHERE rowId = $obj->Poliza LIMIT 1";
					$resp = $db->query($qry);
					if($resp)
					{
						$objeto = $db->fetch_object($resp);
						if($objeto)
						{
							$anioPol = $objeto->anio;
							$mesPol = $objeto->mes;
							$tipoP = $objeto->tipo_pol;
							$numpol = $objeto->cons;
						}
					}
					
					print "<a href='../contab/polizas/fiche.php?fp=1&facid=$numFact'>".formaPol($anioPol,$mesPol,$tipoP,$numpol)."</a>";
				}
			}
			else if($arrayfields['t.'.$key]['label'] == 'Concepto')
			{
				if ($obj->Concepto == "1")
				{
					print "<a>Emitido</a>";
				}
				else
				{
					print "<a>Recibido</a><br>";
				}
					
			}
			else
			{
				print $object->showOutputField($val, $key, $obj->$key, '');
			}
        	
			print '</td>';
        	$sql2="SELECT count(*) as exist FROM ".MAIN_DB_PREFIX."societe WHERE siren='".$obj->RFCemisor."' AND entity='".$conf->entity."'";
				$dd=$db->query($sql2);
				if($dd)
				{
					$rs = $db->fetch_object($dd);
					if($rs->exist == 0)
					{
						$sql2 = "INSERT INTO ".MAIN_DB_PREFIX."societe (nom,fk_pays,siren,idprof4,";
					
						
							$sql2 .= "fournisseur";
							$nom = $obj->NombreEmisor;
						
						$sql2.= ",fk_user_creat)";
						$sql2 .="VALUES(";
						$sql2 .= "'".$nom . "',154,'" .$obj->RFCemisor . "','" .$obj->RFCemisor ."',1,1)";
						
				  }
					else
					{
						$sql2 = "";
					}

				}
				else
				{
					$sql2 = "";
				}
			
			if($sql2 != "")
			{
				//print_r($sql2);
				try
				{
					$es = $db->query($sql2);
					if($es)
					{
						$terceroscreados = true;
					}
					
				}
				catch(Exception $e)
				{
					//print_r($e);
				}
				
			}
			if (! $i) $totalarray['nbfield']++;
			if (! empty($val['isameasure']))
			{
				if (! $i) $totalarray['pos'][$totalarray['nbfield']]='t.'.$key;
				$totalarray['val']['t.'.$key] += $obj->$key;
			}
		}
	}
	// Extra fields
	include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_list_print_fields.tpl.php';
	// Fields from hook
	$parameters=array('arrayfields'=>$arrayfields, 'obj'=>$obj);
	$reshook=$hookmanager->executeHooks('printFieldListValue', $parameters, $object);    // Note that $action and $object may have been modified by hook
	print $hookmanager->resPrint;
	// Action column
	print '<td class="nowrap" align="center">';
	if ($massactionbutton || $massaction)   // If we are in select mode (massactionbutton defined) or if we have already selected and sent an action ($massaction) defined
	{
		$selected=0;
		if (in_array($obj->rowId, $arrayofselected)) $selected=1;
		print '<input id="cb'.$obj->rowId.'" class="flat checkforselect" type="checkbox" name="toselect[]" value="'.$obj->rowId.'"'.($selected?' checked="checked"':'').'>';
	}
	print '</td>';
	if (! $i) $totalarray['nbfield']++;

	print '</tr>';

	$i++;
}

// Show total line
if (isset($totalarray['pos']))
{
	print '<tr class="liste_total">';
	$i=0;
	while ($i < $totalarray['nbfield'])
	{
		$i++;
		if (! empty($totalarray['pos'][$i]))  print '<td align="right">'.price($totalarray['val'][$totalarray['pos'][$i]]).'</td>';
		else
		{
			if ($i == 1)
			{
				if ($num < $limit) print '<td align="left">'.$langs->trans("Total").'</td>';
				else print '<td align="left">'.$langs->trans("Totalforthispage").'</td>';
			}
			else print '<td></td>';
		}
	}
	print '</tr>';
}

// If no record found
if ($num == 0)
{
	$colspan=1;
	foreach($arrayfields as $key => $val) { if (! empty($val['checked'])) $colspan++; }
	print '<tr><td colspan="'.$colspan.'" class="opacitymedium">'.$langs->trans("NoRecordFound").'</td></tr>';
}


$db->free($resql);

$parameters=array('arrayfields'=>$arrayfields, 'sql'=>$sql);
$reshook=$hookmanager->executeHooks('printFieldListFooter', $parameters, $object);    // Note that $action and $object may have been modified by hook
print $hookmanager->resPrint;

print '</table>'."\n";
print '</div>'."\n";

print '</form>'."\n";

if($terceroscreados)
	{
		dol_htmloutput_mesg	("Se han creado nuevos terceros");
	}

if (in_array('builddoc',$arrayofmassactions) && ($nbtotalofrecords === '' || $nbtotalofrecords))
{
	$hidegeneratedfilelistifempty=1;
	if ($massaction == 'builddoc' || $action == 'remove_file' || $show_files) $hidegeneratedfilelistifempty=0;

	require_once DOL_DOCUMENT_ROOT.'/core/class/html.formfile.class.php';
	$formfile = new FormFile($db);

	// Show list of available documents
	$urlsource=$_SERVER['PHP_SELF'].'?sortfield='.$sortfield.'&sortorder='.$sortorder;
	$urlsource.=str_replace('&amp;','&',$param);

	$filedir=$diroutputmassaction;
	$genallowed=$user->rights->mymodule->read;
	$delallowed=$user->rights->mymodule->create;

	print $formfile->showdocuments('massfilesarea_mymodule','',$filedir,$urlsource,0,$delallowed,'',1,1,0,48,1,$param,$title,'','','',null,$hidegeneratedfilelistifempty);
}
function formaPol($anioPol ,$mesPol,$tipoP, $cons)
{
	$arr1 = str_split($anioPol,2);
	if(strlen($mesPol) <= 1)
	{
		$mesPol = "0" . strval($mesPol);
	}
	return strval($arr1[1]) . $mesPol . "-" . $tipoP . "-" . $cons;
}
// End of page
llxFooter();
$db->close();
